server.port: 8888
server.servlet.context-path: /

# 国际化资源路径,一定要有不带local后缀的文件不然识别不到（大坑）
spring.messages.basename: i18n/test

spring.mvc.date-format: yyyy-MM-dd HH:mm:ss
spring:
  datasource:
    username: lwp
    password: Fadai1129,mysql
    url: jdbc:mysql://10.211.55.3:3306/test_db?useUnicode=true&characterEncoding=utf-8&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000



#mybatis:
#  configuration:
#    # 数据库下划线转对象驼峰
#    map-underscore-to-camel-case: true
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

spring.redis:
  host: 10.211.55.3
  port: 6379
  password: reidstest
  lettuce:
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: 1000ms
    shutdown-timeout: 100ms